In [ ]:
import pandas as pd
import numpy as ny
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dataset=pd.read_csv("INC.csv")

In [ ]:
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
Quality=dataset['sex']
dataset['sex']=dataset['sex'].map({'female':0,'male':1}).astype(int)

In [ ]:
CONVERT=dataset["smoker"]
dataset['smoker']=dataset['smoker'].map({'yes':1,'no':0}).astype(int)

In [ ]:
x=dataset.drop('charges',axis=1)

In [ ]:
y=dataset.charges
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [ ]:
dataset['bmi'] = dataset['bmi'].astype(int)

In [ ]:
x

      age  sex     bmi  children  smoker     region
0      19    0  27.900         0       1  southwest
1      18    1  33.770         1       0  southeast
2      28    1  33.000         3       0  southeast
3      33    1  22.705         0       0  northwest
4      32    1  28.880         0       0  northwest
...   ...  ...     ...       ...     ...        ...
1333   50    1  30.970         3       0  northwest
1334   18    0  31.920         0       0  northeast
1335   18    0  36.850         0       0  southeast
1336   21    0  25.800         0       0  southwest
1337   61    0  29.070         0       1  northwest

[1338 rows x 6 columns]

In [ ]:
dataset['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [ ]:
origin=x['region']
x['region']=x['region'].map({'southwest':0,'southeast':1,'northwest':2,'northeast':3}).astype(int)

In [ ]:
x['bmi'] = x['bmi'].round().astype(int)

In [ ]:
x

      age  sex  bmi  children  smoker  region
0      19    0   28         0       1       0
1      18    1   34         1       0       1
2      28    1   33         3       0       1
3      33    1   23         0       0       2
4      32    1   29         0       0       2
...   ...  ...  ...       ...     ...     ...
1333   50    1   31         3       0       2
1334   18    0   32         0       0       3
1335   18    0   37         0       0       1
1336   21    0   26         0       0       0
1337   61    0   29         0       1       2

[1338 rows x 6 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.24,random_state=0)

In [ ]:
from sklearn.svm import SVR
model=SVR()
model.fit(x_train,y_train)

SVR()

In [ ]:
y_pred=model.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error
mse = mean_squared_error(y_test,y_pred)
print(mse)

169974116.3906654

In [ ]:
rmse=ny.sqrt(mse)
print("Root Mean Error:",rmse)
r2_score=r2_score(y_test,y_pred)
print("R2score:",r2_score)

Root Mean Error: 13037.412181513071
R2score: -0.09533713624590145